;;; (C) Copyright 1990 - 2014 by Wade L. Hennessey. All rights reserved.

(defun initialize-format ()
  (setf *format-dispatch-table*
	(make-dispatch-vector
	 (#\B format-print-binary)
	 (#\O format-print-octal)
	 (#\D format-print-decimal)
	 (#\X format-print-hexadecimal)
	 (#\R format-print-radix)
	 (#\F format-fixed)
	 (#\E format-exponential)
	 (#\G format-general-float)
	 (#\A format-princ)
	 (#\C format-print-character)
	 (#\P format-plural)
	 (#\S format-prin1)
	 (#\T format-tab)
	 (#\% format-terpri)
	 (#\& format-freshline)
	 (#\* format-skip-arguments)
	 (#\| format-page)
	 (#\~ format-tilde)
	 (#\$ format-dollars)
	 (#\? format-indirection)
	 (#\^ format-escape)
	 (#\[ format-condition)
	 (#\{ format-iteration)
	 (#\< format-justification)
	 (#\( format-capitalization)
	 (#\newline format-newline))))
